config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'songs#index'
  resources :songs, only: [:index]

  resources :artists, only: [:new, :create, :index], shallow: true do
    resources :songs, only: [:show, :new, :create], param: :slug
  end

  resources :playlists, only: [:new, :create, :show]
  resources :users, only: [:new, :create, :show]

  namespace :admin do
    resources :categories, only: :index
  end

  resources :carts, only: [:create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs

  validates_presence_of :name
end

app/models/cart.rb
class Cart

  attr_reader :contents

  def initialize(initial_content)
    @contents = initial_content || Hash.new(0)
  end

  def total_count
    @contents.values.sum
  end

  def add_song(id)
    @contents[id] = @contents[id] + 1
  end

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs

  before_save :generate_slug

  private
  def generate_slug
    self.slug = title.parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :password
  validates :username, presence: true, uniqueness: true

  has_secure_password

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

    def require_admin
      render file: "/public/404" unless current_admin?
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  before_action :set_cart

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def set_cart
    @cart ||= Cart.new(session[:cart])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def index
    @artists = Artist.all
  end

  private
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    song = Song.find(params[:song_id])
    @cart.add_song(song.id.to_s)
    session[:cart] = @cart.contents
    quantity = @cart.contents[song.id.to_s]

    flash[:notice] = "You now have #{pluralize(quantity, "copy")} of #{song.title} in your cart."
    redirect_to songs_path
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def new
    @playlist = Playlist.new
  end

  def create
    playlist = Playlist.create(playlist_params)
    redirect_to playlist_path(playlist)
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create!(song_params)
    redirect_to song_path(@song.slug)
  end

  def show
    @song = Song.find_by_slug(params[:slug])
  end

  private

  def song_params
    params.require(:song).permit(:title, :length, :play_count)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h2>Admin Categories</h2>

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <li><%= artist.name %></li>
<% end %>

app/views/artists/new.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jukebox1806</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% unless current_user %>
    <p><%= link_to 'Sign up to be a new user', new_user_path %></p>
    <p><%= link_to 'I already have an account', login_path %></p>
    <% else %>
    <p><%= link_to 'Log out', logout_path %></p>
    <% end %>

    <p>Cart: <%= @cart.total_count %></p>

    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: type %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/playlists/new.html.erb
<%= form_for @playlist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<% @songs.each do |song| %>
  <ul>
    <li>Title: <%= song.title %></li>
    <li>Play Count: <%= song.play_count %></li>
  </ul>
  <%= button_to "Add Song", carts_path(song_id: song.id), class: "btn btn-danger" %>
<% end %>

app/views/songs/new.html.erb
<%= form_for [@artist, @song] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :length %>
  <%= f.text_field :length %>
  <%= f.label :play_count %>
  <%= f.text_field :play_count %>

  <%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h1> <%= @song.title %> </h1>
<p>by <%= @song.artist.name %> </p>

app/views/users/new.html.erb
<h1>Sign up to be a new user</h1>

<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
Welcome, <%= current_user.username %>